spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    test-connection: true 
    
