spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true